exercises = [ "squat", "deadlift", "benchpress", "press", "frontsquat", "row",]

[squat]
rounding = 2.5
amraps = "date,reps,weight,rir\r\n2019-07-01,1,155,0\r\n2019-07-01,10,120,0\r\n"

[deadlift]
rounding = 2.5
amraps = "date,reps,weight,rir\r\n2019-07-01,1,200,0\r\n2019-07-01,10,152.5,0\r\n"

[benchpress]
rounding = 2.5
amraps = "date,reps,weight,rir\r\n2019-07-01,1,100,0\r\n2019-07-01,10,75,0\r\n"

[press]
rounding = 1
amraps = "date,reps,weight,rir\r\n2019-07-01,1,65,0\r\n2019-07-01,10,50,0\r\n"

[row]
rounding = 2.5
amraps = "date,reps,weight,rir\r\n2019-07-01,1,100,0\r\n2019-07-01,10,75,0\r\n"

[frontsquat]
rounding = 2.5
amraps = "date,reps,weight,rir\r\n2019-07-01,1,130,0\r\n2019-07-01,10,100,0\r\n"

[measurements]
data = "date,name,measurement\r\n"
options = [ "bodyweight",]
